// Temporary Data
import vector from '../assets/images/Vector.png'
import multiple from '../assets/icons/multiple.png'
import pdf from '../assets/icons/pdf.png'
export const homeCollection = [
    {id:1, thumbnail:vector, heading:'Die Immobilie in der Scheidung', subHeading:'RATGEBER, SCHEIDUNG, EHERECHT', para:'Eine Erbimmobilie kann die familiäre und wirtschaftliche Situation verändern. In diesem Ratgeber verraten wir Ihnen, wie Sie sich im Urwald von Handlungsmöglichkeiten zurecht finden und teilen mit Ihnen den aktuellen Wissensstand. Auch der Immobilienwert spielt eine wichtige Rolle. Sollten Sie den Wert noch nicht ermittelt haben, können Sie diesen mit unserer Marktwertanalyse schnell und unverbindlich online berechnen lassen.', buttonColor:'#034154', optionsImg:[multiple, multiple, pdf]},
    {id:2, thumbnail:vector, heading:'Die Immobilie in der Scheidung', subHeading:'RATGEBER, SCHEIDUNG, EHERECHT', para:'Eine Erbimmobilie kann die familiäre und wirtschaftliche Situation verändern. In diesem Ratgeber verraten wir Ihnen, wie Sie sich im Urwald von Handlungsmöglichkeiten zurecht finden und teilen mit Ihnen den aktuellen Wissensstand. Auch der Immobilienwert spielt eine wichtige Rolle. Sollten Sie den Wert noch nicht ermittelt haben, können Sie diesen mit unserer Marktwertanalyse schnell und unverbindlich online berechnen lassen.', buttonColor:'#459E97', optionsImg:[multiple, multiple, pdf]},
    {id:3, thumbnail:vector, heading:'Die Immobilie in der Scheidung', subHeading:'RATGEBER, SCHEIDUNG, EHERECHT', para:'Eine Erbimmobilie kann die familiäre und wirtschaftliche Situation verändern. In diesem Ratgeber verraten wir Ihnen, wie Sie sich im Urwald von Handlungsmöglichkeiten zurecht finden und teilen mit Ihnen den aktuellen Wissensstand. Auch der Immobilienwert spielt eine wichtige Rolle. Sollten Sie den Wert noch nicht ermittelt haben, können Sie diesen mit unserer Marktwertanalyse schnell und unverbindlich online berechnen lassen.', buttonColor:'#034154', optionsImg:[multiple, multiple, pdf]},
    {id:3, thumbnail:vector, heading:'Die Immobilie in der Scheidung', subHeading:'RATGEBER, SCHEIDUNG, EHERECHT', para:'Eine Erbimmobilie kann die familiäre und wirtschaftliche Situation verändern. In diesem Ratgeber verraten wir Ihnen, wie Sie sich im Urwald von Handlungsmöglichkeiten zurecht finden und teilen mit Ihnen den aktuellen Wissensstand. Auch der Immobilienwert spielt eine wichtige Rolle. Sollten Sie den Wert noch nicht ermittelt haben, können Sie diesen mit unserer Marktwertanalyse schnell und unverbindlich online berechnen lassen.', buttonColor:'#034154', optionsImg:[multiple, multiple, pdf]},
    {id:3, thumbnail:vector, heading:'Die Immobilie in der Scheidung', subHeading:'RATGEBER, SCHEIDUNG, EHERECHT', para:'Eine Erbimmobilie kann die familiäre und wirtschaftliche Situation verändern. In diesem Ratgeber verraten wir Ihnen, wie Sie sich im Urwald von Handlungsmöglichkeiten zurecht finden und teilen mit Ihnen den aktuellen Wissensstand. Auch der Immobilienwert spielt eine wichtige Rolle. Sollten Sie den Wert noch nicht ermittelt haben, können Sie diesen mit unserer Marktwertanalyse schnell und unverbindlich online berechnen lassen.', buttonColor:'#034154', optionsImg:[multiple, multiple, pdf]},
    
 
]